env: dev

env_config:
  dev:
    url: http://localhost:4000
  prod:
    url: https://github.io/OutbackMan/something
    
url: site.env_config[site.env].url

timezone: Australia/Sydney

profile: true
strict_front_matter: true

liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true

primary_color: "#444444"
lightened_primary_color: "#525252"
secondary_color: rgba(20, 20, 20, 0.4)
